output "availability_zones" {}
output "nat_gateway_count" {}
output "nat_gateway_public_ips" {}
output "num_availability_zones" {}
output "private_subnet_ids" {}
output "private_subnet_cidr_blocks" {}
output "private_subnet_route_table_ids" {}
output "private_subnets" {}
output "private_subnets_route_table_ids" {}
output "public_subnet_cidr_blocks" {}
output "public_subnet_ids" {}
output "public_subnet_route_table_id" {}
output "public_subnets" {}
output "public_subnets_network_acl_id" {}
output "vpc_cidr_block" {}
output "vpc_id" {}
output "vpc_name" {}
output "vpc_ready" {}
