fail_fast: true
repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
        # always_run: true
      - id: tflint
        # always_run: true
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-system
        args: ["markdown", "document", "--output-file", "README.md", "--output-mode", "replace", "--hide-empty", "--recursive", "."]
        stages: [commit]
        # always_run: true