formatter: "markdown document"

version: "0.16"

recursive:
  enabled: true

content: |-
  {{ .Requirements }}

  ## Sample Usage

  ```hcl
  module "example" {
    {{"\n"}}
    {{"\t"}} source  = "github.com/Cyber4All/terraform-cyber4all-catalog//modules/<REPLACE_WITH_MODULE>?ref=v<REPLACE_WITH_VERSION>"
    {{"\n"}}
  
  {{- if .Module.RequiredInputs }}
    {{"\t"}} # --------------------------------------------
    {{"\t"}} # Required variables
    {{"\t"}} # --------------------------------------------
    {{"\n"}}
    {{- range .Module.RequiredInputs }}
      {{"\t #"}} {{ .Description }}
      {{"\t"}} {{ .Name }}  = {{ .Type }}
      {{"\n"}}
    {{- end }}
  {{- end }}
  
  {{- if .Module.OptionalInputs }}
    {{"\t"}} # --------------------------------------------
    {{"\t"}} # Optional variables
    {{"\t"}} # --------------------------------------------
    {{"\n"}}
    {{- range .Module.OptionalInputs }}
      {{"\t #"}} {{ .Description }}
      {{"\t"}} {{ .Name }}  = {{ .Type }}
      {{"\n"}}
    {{- end }}
  {{- end }}
  
  }
  ```
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: README.md
  mode: inject

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true