version: 2.1

orbs:
  cyber4all: cyber4all/orb@1.3

workflows:
  cd:
    when: # runs when merge into main
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - cyber4all/release:
          context: [Github]
          tag: "$(./version.sh -r)"
