version: 2.1

jobs:
  tflint:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          command: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - run:
          command: |
            for i in $(./.githooks/scripts/get-terraform-dirs.py)
            do
              tflint $i
            done

workflows:
  continuous-integration:
    jobs:
      # - tflint
      - tfsec
