version: 2.1

jobs:
  precommit:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          command: |
            pip install pre-commit
            pre-commit install
            pre-commit run --all-files 

  tfsec:
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - run:
          command: |
            go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
      - run:
          command: |
            tfsec ./modules --concise-output -m HIGH -s

workflows:
  continuous-integration:
    jobs:
      # - tflint
      - precommit
      - tfsec
