version: 2.1
orbs:
  terraform: circleci/terraform@3.1.0

jobs:
  precommit:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Precommit Strategy
          command: |
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install terraform
            pip install pre-commit
            pre-commit install
            pre-commit run --all-files 

  tfsec:
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - run:
          command: |
            go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
      - run:
          command: |
            tfsec ./modules --concise-output -m HIGH -s

workflows:
  continuous-integration:
    jobs:
      # - tflint
      - precommit
      - tfsec
