version: 2.1

orbs:
  gh: circleci/github-cli@2.1.1

jobs:
  tflint:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          command: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - run:
          command: |
            for i in $(./.githooks/scripts/get-terraform-dirs.py)
            do
              tflint $i
            done

  tfsec:
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - run:
          command: |
            go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
      - run:
          command: |
            tfsec ./modules --concise-output -m HIGH -s

workflows:
  continuous-integration:
    jobs:
      - tflint
      - tfsec

  continuous-deployment:
    when:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - gh/release:
          context: [Github]
          tag: "v$(jq -r '.version' package.json)"
          token: GH_PAT

      