output "ecs_service_arn" {
  description = "ARN generated by the service"
  value       = aws_ecs_service.example.id
}

output "ecs_service_name" {
  description = "Name of the service"
  value       = aws_ecs_service.example.name
}