output "task_def_arn" {
  description = "ARN generated by the task definition"
  value = aws_ecs_task_definition.example.arn
}

output "task_def_revision" {
  description = "Revision of the task in a particular family"
  value = aws_ecs_task_definition.example.revision
}

output "task_def_tags" {
  description = "Map of tags assigned to task definition"
  value = aws_ecs_task_definition.example.tags_all
}